apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
spec:
  type: NodePort
  selector:
    app: jenkins-demo
  ports:
    - port: 8081          # External port exposed by the service
      targetPort: 8080    # Internal port the container listens to
      nodePort: 30001     # Optional: The specific port exposed on the node (if you need a custom NodePort)
